-- 코드를 입력하세요
SELECT
    CAR_ID,
    ROUND(avg(DATEDIFF(END_DATE,START_DATE)+1),1) AVERAGE_DURATION
from CAR_RENTAL_COMPANY_RENTAL_HISTORY H
group by CAR_ID
having AVERAGE_DURATION >= 7.0
order by AVERAGE_DURATION desc, CAR_ID desc;