-- 코드를 입력하세요
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    sum(P.PRICE * O.AMOUNT) TOTAL_SALES
from FOOD_PRODUCT P
join FOOD_ORDER O
on P.PRODUCT_ID = O.PRODUCT_ID
where O.PRODUCE_DATE between '2022-05-01' and '2022-05-31'
group by PRODUCT_NAME
order by TOTAL_SALES desc, P.PRODUCT_ID;